-- Topar seed data. Paste into Supabase SQL Editor AFTER 0001_schema.sql.
-- Safe to re-run any time (e.g. right before the demo to refresh deadlines):
-- it wipes catalog + groups and re-inserts everything. Profiles are untouched.

delete from public.group_participants;
delete from public.group_buys;
delete from public.products;

insert into public.products (slug, title, description, category, marketplace, price_usd, rating, orders_count, image_url) values
-- electronics
('wireless-earbuds',
 jsonb_build_object('ru','Беспроводные наушники TWS Pro','kk','TWS Pro сымсыз құлаққабы','en','TWS Pro Wireless Earbuds'),
 jsonb_build_object('ru','Шумоподавление, до 30 часов работы с кейсом, Bluetooth 5.3.','kk','Шуды басу, кейспен 30 сағатқа дейін жұмыс, Bluetooth 5.3.','en','Noise cancellation, up to 30 hours with the case, Bluetooth 5.3.'),
 'electronics','aliexpress',19.99,4.7,45230,'https://picsum.photos/seed/wireless-earbuds/600/600'),
('smart-watch',
 jsonb_build_object('ru','Смарт-часы Fit X8','kk','Fit X8 смарт-сағаты','en','Fit X8 Smart Watch'),
 jsonb_build_object('ru','Пульс, сон, 100+ спортивных режимов, до 7 дней без зарядки.','kk','Пульс, ұйқы, 100+ спорт режимі, зарядсыз 7 күнге дейін.','en','Heart rate, sleep tracking, 100+ sport modes, 7-day battery.'),
 'electronics','temu',32.50,4.5,28900,'https://picsum.photos/seed/smart-watch/600/600'),
('power-bank-20000',
 jsonb_build_object('ru','Пауэрбанк 20 000 мА·ч','kk','Пауэрбанк 20 000 мА·сағ','en','20,000 mAh Power Bank'),
 jsonb_build_object('ru','Быстрая зарядка 22.5 Вт, два USB-порта и Type-C.','kk','Жылдам зарядтау 22.5 Вт, екі USB порты және Type-C.','en','22.5W fast charging, dual USB ports and Type-C.'),
 'electronics','aliexpress',24.90,4.8,67400,'https://picsum.photos/seed/power-bank-20000/600/600'),
('robot-vacuum',
 jsonb_build_object('ru','Робот-пылесос SmartClean','kk','SmartClean робот-шаңсорғышы','en','SmartClean Robot Vacuum'),
 jsonb_build_object('ru','Лидар-навигация, влажная уборка, управление со смартфона.','kk','Лидар навигациясы, ылғалды тазалау, смартфоннан басқару.','en','Lidar navigation, mopping, smartphone control.'),
 'electronics','amazon',189.00,4.6,8200,'https://picsum.photos/seed/robot-vacuum/600/600'),
('bt-speaker',
 jsonb_build_object('ru','Bluetooth-колонка BoomGo','kk','BoomGo Bluetooth үндеткіші','en','BoomGo Bluetooth Speaker'),
 jsonb_build_object('ru','Мощный бас, защита от воды IPX7, 24 часа музыки.','kk','Қуатты бас, IPX7 суға төзімділік, 24 сағат музыка.','en','Punchy bass, IPX7 waterproof, 24 hours of playtime.'),
 'electronics','temu',27.80,4.4,19850,'https://picsum.photos/seed/bt-speaker/600/600'),
('action-camera',
 jsonb_build_object('ru','Экшн-камера 4K UltraGo','kk','UltraGo 4K экшн-камерасы','en','UltraGo 4K Action Camera'),
 jsonb_build_object('ru','Съёмка 4K/60fps, стабилизация, аквабокс в комплекте.','kk','4K/60fps түсірілім, тұрақтандыру, аквабокс жинақта.','en','4K/60fps recording, stabilization, waterproof case included.'),
 'electronics','aliexpress',79.00,4.5,12300,'https://picsum.photos/seed/action-camera/600/600'),
('mini-projector',
 jsonb_build_object('ru','Мини-проектор HomeCinema','kk','HomeCinema мини-проекторы','en','HomeCinema Mini Projector'),
 jsonb_build_object('ru','Full HD, экран до 120 дюймов, Wi-Fi и Bluetooth.','kk','Full HD, 120 дюймге дейін экран, Wi-Fi және Bluetooth.','en','Full HD, up to 120-inch screen, Wi-Fi and Bluetooth.'),
 'electronics','amazon',95.00,4.3,5600,'https://picsum.photos/seed/mini-projector/600/600'),
('phone-gimbal',
 jsonb_build_object('ru','Стабилизатор для смартфона','kk','Смартфонға арналған стабилизатор','en','Smartphone Gimbal'),
 jsonb_build_object('ru','Трёхосевая стабилизация, отслеживание лица, складной.','kk','Үш осьті тұрақтандыру, бетті қадағалау, жиналмалы.','en','3-axis stabilization, face tracking, foldable.'),
 'electronics','aliexpress',45.00,4.6,7800,'https://picsum.photos/seed/phone-gimbal/600/600'),
-- fashion
('running-sneakers',
 jsonb_build_object('ru','Кроссовки AirRun','kk','AirRun кроссовкасы','en','AirRun Sneakers'),
 jsonb_build_object('ru','Лёгкие дышащие кроссовки с амортизирующей подошвой.','kk','Жеңіл, ауа өткізетін, амортизациялық табаны бар кроссовка.','en','Lightweight breathable sneakers with cushioned sole.'),
 'fashion','temu',38.00,4.5,33100,'https://picsum.photos/seed/running-sneakers/600/600'),
('puffer-jacket',
 jsonb_build_object('ru','Куртка-пуховик Urban','kk','Urban мамық күртешесі','en','Urban Puffer Jacket'),
 jsonb_build_object('ru','Тёплый пуховик до −25°C, водоотталкивающая ткань.','kk','−25°C дейін жылы күртеше, су өткізбейтін мата.','en','Warm down jacket rated to −25°C, water-repellent fabric.'),
 'fashion','aliexpress',54.00,4.4,14500,'https://picsum.photos/seed/puffer-jacket/600/600'),
('crossbody-bag',
 jsonb_build_object('ru','Сумка кросс-боди','kk','Кросс-боди сөмкесі','en','Crossbody Bag'),
 jsonb_build_object('ru','Компактная сумка из экокожи с регулируемым ремнём.','kk','Реттелетін бауы бар экотеріден жасалған шағын сөмке.','en','Compact vegan-leather bag with adjustable strap.'),
 'fashion','temu',16.90,4.6,41200,'https://picsum.photos/seed/crossbody-bag/600/600'),
('polar-sunglasses',
 jsonb_build_object('ru','Очки поляризационные','kk','Поляризациялық көзілдірік','en','Polarized Sunglasses'),
 jsonb_build_object('ru','Защита UV400, поляризационные линзы, унисекс.','kk','UV400 қорғанысы, поляризациялық линзалар, унисекс.','en','UV400 protection, polarized lenses, unisex.'),
 'fashion','aliexpress',9.90,4.3,52600,'https://picsum.photos/seed/polar-sunglasses/600/600'),
('oversize-hoodie',
 jsonb_build_object('ru','Худи оверсайз Basic','kk','Basic оверсайз худиі','en','Basic Oversize Hoodie'),
 jsonb_build_object('ru','Плотный хлопок 360 г/м², мягкий начёс внутри.','kk','Тығыз мақта 360 г/м², іші жұмсақ түкті.','en','Dense 360 g/m² cotton, soft fleece inside.'),
 'fashion','temu',21.50,4.7,26700,'https://picsum.photos/seed/oversize-hoodie/600/600'),
('silk-scarf',
 jsonb_build_object('ru','Шёлковый платок','kk','Жібек орамал','en','Silk Scarf'),
 jsonb_build_object('ru','Натуральный шёлк, 90×90 см, подарочная упаковка.','kk','Табиғи жібек, 90×90 см, сыйлық қаптамасы.','en','Natural silk, 90×90 cm, gift packaging.'),
 'fashion','aliexpress',12.40,4.5,9300,'https://picsum.photos/seed/silk-scarf/600/600'),
('leather-belt',
 jsonb_build_object('ru','Кожаный ремень Classic','kk','Classic былғары белдігі','en','Classic Leather Belt'),
 jsonb_build_object('ru','Натуральная кожа, автоматическая пряжка.','kk','Табиғи былғары, автоматты тоғасы.','en','Genuine leather with automatic buckle.'),
 'fashion','amazon',14.00,4.6,11800,'https://picsum.photos/seed/leather-belt/600/600'),
-- home
('air-fryer',
 jsonb_build_object('ru','Аэрогриль CrispyPro 5 л','kk','CrispyPro аэрогрилі 5 л','en','CrispyPro Air Fryer 5L'),
 jsonb_build_object('ru','Готовка без масла, 8 программ, таймер и LED-дисплей.','kk','Майсыз пісіру, 8 бағдарлама, таймер және LED дисплей.','en','Oil-free cooking, 8 programs, timer and LED display.'),
 'home','amazon',62.00,4.8,23400,'https://picsum.photos/seed/air-fryer/600/600'),
('led-strip',
 jsonb_build_object('ru','LED-лента RGB 10 м','kk','RGB LED жолағы 10 м','en','RGB LED Strip 10m'),
 jsonb_build_object('ru','16 млн цветов, управление с приложения, синхронизация с музыкой.','kk','16 млн түс, қосымшадан басқару, музыкамен синхрондау.','en','16M colors, app control, music sync.'),
 'home','aliexpress',11.50,4.4,78900,'https://picsum.photos/seed/led-strip/600/600'),
('memory-pillow',
 jsonb_build_object('ru','Подушка с эффектом памяти','kk','Жады эффектісі бар жастық','en','Memory Foam Pillow'),
 jsonb_build_object('ru','Ортопедическая форма, гипоаллергенный чехол.','kk','Ортопедиялық пішін, гипоаллергенді тыс.','en','Orthopedic shape, hypoallergenic cover.'),
 'home','temu',18.90,4.6,15600,'https://picsum.photos/seed/memory-pillow/600/600'),
('electric-kettle',
 jsonb_build_object('ru','Электрочайник стеклянный','kk','Шыны электр шәйнегі','en','Glass Electric Kettle'),
 jsonb_build_object('ru','1.8 л, LED-подсветка, автоотключение.','kk','1.8 л, LED жарықтандыру, автоматты өшу.','en','1.8L, LED light, auto shut-off.'),
 'home','amazon',25.40,4.5,9700,'https://picsum.photos/seed/electric-kettle/600/600'),
('aroma-diffuser',
 jsonb_build_object('ru','Аромадиффузор ультразвуковой','kk','Ультрадыбыстық аромадиффузор','en','Ultrasonic Aroma Diffuser'),
 jsonb_build_object('ru','300 мл, 7 цветов подсветки, тихий режим для сна.','kk','300 мл, 7 түсті жарық, ұйқыға арналған тыныш режим.','en','300ml, 7-color light, quiet sleep mode.'),
 'home','aliexpress',15.80,4.5,18200,'https://picsum.photos/seed/aroma-diffuser/600/600'),
('storage-organizer',
 jsonb_build_object('ru','Органайзеры для хранения, 6 шт','kk','Сақтау органайзері, 6 дана','en','Storage Organizers, 6 pcs'),
 jsonb_build_object('ru','Складные коробы для одежды и белья.','kk','Киім мен төсек-орынға арналған жиналмалы қораптар.','en','Foldable boxes for clothes and linen.'),
 'home','temu',13.20,4.3,31500,'https://picsum.photos/seed/storage-organizer/600/600'),
('fleece-blanket',
 jsonb_build_object('ru','Плед флисовый 200×220','kk','Флис жамылғысы 200×220','en','Fleece Blanket 200×220'),
 jsonb_build_object('ru','Мягкий двусторонний флис, не электризуется.','kk','Жұмсақ екі жақты флис, электрленбейді.','en','Soft double-sided fleece, anti-static.'),
 'home','aliexpress',17.60,4.7,12900,'https://picsum.photos/seed/fleece-blanket/600/600'),
-- beauty
('hair-dryer-brush',
 jsonb_build_object('ru','Фен-щётка StylePro 5-в-1','kk','StylePro фен-қылшағы 5-і 1-де','en','StylePro 5-in-1 Hair Dryer Brush'),
 jsonb_build_object('ru','Сушка, укладка и объём, 5 насадок, ионизация.','kk','Кептіру, сәндеу және көлем, 5 саптама, иондау.','en','Dry, style and volumize, 5 attachments, ionic care.'),
 'beauty','aliexpress',34.90,4.5,38700,'https://picsum.photos/seed/hair-dryer-brush/600/600'),
('led-face-mask',
 jsonb_build_object('ru','LED-маска для лица','kk','Бетке арналған LED-маска','en','LED Face Mask'),
 jsonb_build_object('ru','7 режимов светотерапии для ухода за кожей.','kk','Тері күтіміне арналған 7 жарық терапиясы режимі.','en','7 light-therapy modes for skincare.'),
 'beauty','amazon',49.00,4.2,4300,'https://picsum.photos/seed/led-face-mask/600/600'),
('perfume-set',
 jsonb_build_object('ru','Набор мини-парфюмов, 5 шт','kk','Мини-парфюм жинағы, 5 дана','en','Mini Perfume Set, 5 pcs'),
 jsonb_build_object('ru','Пять ароматов по 10 мл в подарочной коробке.','kk','Сыйлық қорабындағы 10 мл бес хош иіс.','en','Five 10ml scents in a gift box.'),
 'beauty','temu',22.00,4.4,17800,'https://picsum.photos/seed/perfume-set/600/600'),
('skincare-set',
 jsonb_build_object('ru','Набор уходовой косметики','kk','Күтім косметикасы жинағы','en','Skincare Set'),
 jsonb_build_object('ru','Очищение, тонер, сыворотка и крем — полный уход.','kk','Тазарту, тонер, сарысу және крем — толық күтім.','en','Cleanser, toner, serum and cream — a full routine.'),
 'beauty','aliexpress',28.50,4.6,21900,'https://picsum.photos/seed/skincare-set/600/600'),
('nail-lamp-kit',
 jsonb_build_object('ru','Лампа для маникюра + гель-лаки','kk','Маникюр шамы + гель-лактар','en','Nail Lamp + Gel Polish Kit'),
 jsonb_build_object('ru','UV/LED-лампа 86 Вт и набор из 12 гель-лаков.','kk','86 Вт UV/LED шам және 12 гель-лак жинағы.','en','86W UV/LED lamp with a set of 12 gel polishes.'),
 'beauty','temu',26.70,4.5,14100,'https://picsum.photos/seed/nail-lamp-kit/600/600'),
('jade-roller',
 jsonb_build_object('ru','Роллер для лица из нефрита','kk','Нефриттен жасалған бет роллері','en','Jade Face Roller'),
 jsonb_build_object('ru','Натуральный камень, снимает отёчность, в комплекте гуаша.','kk','Табиғи тас, ісінуді басады, жинақта гуаша.','en','Natural stone, reduces puffiness, gua sha included.'),
 'beauty','aliexpress',7.90,4.3,25800,'https://picsum.photos/seed/jade-roller/600/600'),
('electric-cleanser',
 jsonb_build_object('ru','Щётка для умывания','kk','Бет жууға арналған қылшақ','en','Facial Cleansing Brush'),
 jsonb_build_object('ru','Силиконовая, водонепроницаемая, 5 режимов вибрации.','kk','Силиконды, су өткізбейді, 5 діріл режимі.','en','Silicone, waterproof, 5 vibration modes.'),
 'beauty','temu',12.30,4.4,9800,'https://picsum.photos/seed/electric-cleanser/600/600'),
-- sports
('yoga-mat',
 jsonb_build_object('ru','Коврик для йоги 6 мм','kk','Йога төсеніші 6 мм','en','Yoga Mat 6mm'),
 jsonb_build_object('ru','Нескользящее покрытие, ремешок для переноски.','kk','Сырғымайтын беті, тасымалдау бауы.','en','Non-slip surface, carrying strap.'),
 'sports','temu',13.90,4.6,29400,'https://picsum.photos/seed/yoga-mat/600/600'),
('dumbbells-set',
 jsonb_build_object('ru','Разборные гантели 2×10 кг','kk','Құрастырмалы гантельдер 2×10 кг','en','Adjustable Dumbbells 2×10 kg'),
 jsonb_build_object('ru','Регулируемый вес, соединяются в штангу.','kk','Реттелетін салмақ, штангаға біріктіріледі.','en','Adjustable weight, converts to a barbell.'),
 'sports','amazon',58.00,4.7,6900,'https://picsum.photos/seed/dumbbells-set/600/600'),
('massage-gun',
 jsonb_build_object('ru','Массажный пистолет Relax','kk','Relax массаж пистолеті','en','Relax Massage Gun'),
 jsonb_build_object('ru','6 насадок, 30 скоростей, тихий мотор.','kk','6 саптама, 30 жылдамдық, тыныш мотор.','en','6 heads, 30 speeds, quiet motor.'),
 'sports','aliexpress',36.50,4.5,22600,'https://picsum.photos/seed/massage-gun/600/600'),
('resistance-bands',
 jsonb_build_object('ru','Набор фитнес-резинок','kk','Фитнес-резеңкелер жинағы','en','Resistance Bands Set'),
 jsonb_build_object('ru','5 уровней сопротивления, чехол в комплекте.','kk','5 кедергі деңгейі, қапшығы жинақта.','en','5 resistance levels, pouch included.'),
 'sports','temu',8.90,4.5,47300,'https://picsum.photos/seed/resistance-bands/600/600'),
('thermo-bottle',
 jsonb_build_object('ru','Термобутылка 1 л','kk','Термобөтелке 1 л','en','Thermo Bottle 1L'),
 jsonb_build_object('ru','Держит тепло 12 часов, холод — 24 часа.','kk','Жылуды 12 сағат, суықты 24 сағат сақтайды.','en','Keeps drinks hot for 12h, cold for 24h.'),
 'sports','aliexpress',11.20,4.6,35200,'https://picsum.photos/seed/thermo-bottle/600/600'),
('running-backpack',
 jsonb_build_object('ru','Рюкзак спортивный 25 л','kk','Спорттық рюкзак 25 л','en','Sports Backpack 25L'),
 jsonb_build_object('ru','Отделение для обуви, влагозащита, светоотражатели.','kk','Аяқ киім бөлімі, ылғалдан қорғау, шағылыстырғыштар.','en','Shoe compartment, water-resistant, reflective details.'),
 'sports','temu',19.80,4.4,13700,'https://picsum.photos/seed/running-backpack/600/600'),
('jump-rope-smart',
 jsonb_build_object('ru','Умная скакалка со счётчиком','kk','Санағышы бар смарт секіртпе','en','Smart Jump Rope with Counter'),
 jsonb_build_object('ru','Счётчик прыжков и калорий, регулируемая длина.','kk','Секіру мен калория санағышы, реттелетін ұзындық.','en','Jump and calorie counter, adjustable length.'),
 'sports','aliexpress',10.50,4.3,16400,'https://picsum.photos/seed/jump-rope-smart/600/600');

-- Group buys. participants_count here is the demo baseline; the trigger
-- increments/decrements from it when real users join or leave.
-- wireless-earbuds is deliberately at 9/10: one live join on stage crosses
-- the −15% tier and the price visibly drops.
insert into public.group_buys (product_id, participants_count, deadline, status) values
((select id from public.products where slug = 'wireless-earbuds'),  9, now() + interval '26 hours', 'active'),
((select id from public.products where slug = 'smart-watch'),      23, now() + interval '6 hours',  'active'),
((select id from public.products where slug = 'power-bank-20000'), 41, now() + interval '14 hours', 'active'),
((select id from public.products where slug = 'robot-vacuum'),     12, now() + interval '3 days',   'active'),
((select id from public.products where slug = 'running-sneakers'), 18, now() + interval '30 hours', 'active'),
((select id from public.products where slug = 'crossbody-bag'),    35, now() + interval '9 hours',  'active'),
((select id from public.products where slug = 'air-fryer'),        27, now() + interval '2 days',   'active'),
((select id from public.products where slug = 'led-strip'),        44, now() + interval '5 hours',  'active'),
((select id from public.products where slug = 'hair-dryer-brush'), 31, now() + interval '20 hours', 'active'),
((select id from public.products where slug = 'yoga-mat'),         15, now() + interval '28 hours', 'active'),
((select id from public.products where slug = 'massage-gun'),       8, now() + interval '40 hours', 'active'),
((select id from public.products where slug = 'polar-sunglasses'), 37, now() - interval '2 hours',  'expired');
